name: Build CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build for ${{ matrix.target }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: Linux
            os: ubuntu-latest
          - target: Darwin
            os: macos-latest
          - target: Windows_NT
            os: windows-latest
          
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install dependencies (Linux)
        if: matrix.target == 'Linux'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            xauth \
            libx11-dev \
            libxcursor-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxi-dev \
            libxext-dev \
            libgl1-mesa-dev \
            libasound2-dev

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --config Release --parallel
      
      - name: Smoke test on Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          set +e
          
          timeout --signal=TERM 10s xvfb-run -a ./build/cnake
          EXIT_CODE=$?
          
          if [ "$EXIT_CODE" -eq 124 ]; then
            echo "Success: The game ran smoothly for 10 seconds."
            exit 0
          else
            echo "Error: The game crashed or closed prematurely (code $EXIT_CODE)."
            exit 1
          fi

      - name: Smoke test on macOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          ./build/cnake &
          PID=$!
          
          for i in {1..10}; do
            if ! kill -0 $PID 2>/dev/null; then
              wait $PID
              EXIT_CODE=$?
              echo "Error: The game crashed at the $i second  (code $EXIT_CODE)."
              exit 1
            fi
            sleep 1
          done
          
          kill $PID
          echo "Success: The game ran smoothly for 10 seconds."

      - name: Smoke test on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $executable = Join-Path $env:GITHUB_WORKSPACE "build\Release\cnake.exe"
          $process = Start-Process -FilePath $executable -WorkingDirectory (Split-Path $executable) -PassThru
          
          if ($process.WaitForExit(10000)) {
              Write-Error "Error: The game crashed or closed prematurely (code $($process.ExitCode))"
              exit 1
          } else {
              Stop-Process -Id $process.Id -Force
              Write-Host "Success: The game ran smoothly for 10 seconds."
              exit 0
          }